-------- 이벤트 테이블 --------
CREATE TABLE MC_ATTACH(
    UUID VARCHAR2(100) CONSTRAINT UK_UUID UNIQUE,								-- uuid
    UPLOAD_PATH VARCHAR2(300) NOT NULL,												-- 저장장소
    FILE_NAME VARCHAR2(200) NOT NULL,												-- 파일이름
    MID VARCHAR2(50) CONSTRAINT FK_ATTACH_MID REFERENCES MC_MEMBER(MID) ON DELETE CASCADE,			--(2024/2/16)수정 mid 참조
    MOV_CODE CHAR(8) CONSTRAINT FK_ATTACH_MOV_CODE REFERENCES MC_MOVIE(MOV_CODE) ON DELETE CASCADE-- mov_code 참조
);

DROP TABLE MC_ATTACH;