-------- 이벤트 테이블 --------
CREATE TABLE MC_EVENT(
    ENO NUMBER PRIMARY KEY,
    MID VARCHAR2(20) CONSTRAINT FK_MID REFERENCES MC_MEMBER(MID),
    EDATE DATE DEFAULT SYSDATE,
    ECHECK CHAR(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_ENO;