CREATE TABLE MC_NOTICE (
    NNO NUMBER NOT NULl CONSTRAINT PK_NNO PRIMARY KEY,				--공지번호
    NTITLE VARCHAR2(100 BYTE) NOT NULL,		--공지제목
    NCONTENT VARCHAR2(4000 BYTE) NOT NULL,	--공지내용
    NREGDATE DATE DEFAULT sysdate,		--공지날짜
    NCOUNT NUMBER DEFAULT 0			--공지 조회수
);

create sequence seq_nno;