-------- 이벤트 테이블 --------
CREATE TABLE MC_REVIEW(
    MID VARCHAR2(20) CONSTRAINT FK_REVIEW_MID REFERENCES MC_MEMBER(MID),
    R_CONTENT VARCHAR2(1000) NOT NULL,
    R_DATE DATE DEFAULT SYSDATE
);

DROP TABLE MC_REVIEW;