-------- 이벤트 테이블 --------
CREATE TABLE MC_REVIEW(
    MID VARCHAR2(20) CONSTRAINT FK_REVIEW_MID REFERENCES MC_MEMBER(MID),
    MOV_CODE CHAR(8) CONSTRAINT FK_REVIEW_MOV_CODE REFERENCES MC_MOVIE(MOV_CODE) ON DELETE CASCADE,
    R_CONTENT VARCHAR2(1000) NOT NULL,
    R_DATE DATE DEFAULT SYSDATE
);

DROP TABLE MC_REVIEW;